{
 "title": "Delivery Time Prediction MLOps",
 "time": { "from": "2025-05-03T07:25:19.632Z", "to": "2025-05-03T07:35:19.632Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Prediction Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_success_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prediction_failure_count_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(request_count_total)\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input Distance Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(prediction_input_distance_km_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(prediction_latency_seconds_sum[1m]) / rate(prediction_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Seconds Total ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}