train:
  test_size: 0.2            
  random_state: 42          
  cv_folds: 3                
  n_iter_search: 10          # round of Randomized Search (Hyperparameter tuning)

model:
  experiment_name: "DeliveryTimePrediction"
  tracking_uri: "http://127.0.0.1:5000"
  target_column: "TRIP_DURATION_MINUTES" 

xgboost:
  n_estimators: [100, 200, 300]
  learning_rate: [0.01, 0.05, 0.1]
  max_depth: [3, 5, 7]
  subsample: [0.7, 0.8, 1.0]
  colsample_bytree: [0.7, 0.8, 1.0]

lightgbm:
  n_estimators: [100, 200, 300]
  learning_rate: [0.01, 0.03, 0.05]
  num_leaves: [20, 31, 40]
  min_child_samples: [10, 20, 30]
  subsample: [0.7, 0.8, 1.0]